# Generated by Django 6.0.4 on 2026-07-22 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_fine_amount_paid_fine_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='affected_week',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='fine',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'AUTOMATIC')), fields=('member', 'affected_week'), name='unique_automatic_fine_member_week'),
        ),
    ]
