# Generated by Django 4.2.5 on 2025-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_alter_depositsubmission_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsubmission',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
