# Generated by Django 6.0.4 on 2026-07-13 14:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_alter_depositsubmission_proof'),
        ('fines', '0002_fine_amount_paid_fine_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubmission',
            name='fine_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='land_savings_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='selected_fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_deposits', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name='DepositAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='deposits.depositsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fine_allocation', to='deposits.depositsubmission')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='fines.fine')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='deposits.savingsaccount'),
        ),
        migrations.CreateModel(
            name='WeeklySavingsAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_allocations', to='deposits.depositsubmission')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_allocations', to='deposits.savingsaccount')),
            ],
            options={
                'ordering': ['week_start', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deposit', 'week_start'), name='unique_deposit_week_allocation')],
            },
        ),
    ]
