# Generated by Django 6.0.4 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0007_memberprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='weekly_contribution',
            field=models.DecimalField(decimal_places=2, default=20000, help_text='Required Land Savings contribution per week', max_digits=10),
        ),
    ]
