# Generated by Django 6.0.4 on 2026-07-22 10:06

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0008_groupsettings_weekly_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='automatic_fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), help_text='Fine proposed for a late or missed weekly contribution', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='automatic_fines_start_period',
            field=models.DateField(blank=True, help_text='First weekly period eligible for automatic fines; initialized on first reconciliation', null=True),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='weekly_deadline_time',
            field=models.TimeField(default=datetime.time(23, 59), help_text='Submission cutoff time in the configured Django time zone'),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='weekly_deadline_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text='Weekday on which weekly Land Savings submissions close'),
        ),
    ]
